/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ViButton {
        "appearance": string;
        "text": string;
    }
    interface ViModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isopen": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLViButtonElement extends Components.ViButton, HTMLStencilElement {
    }
    var HTMLViButtonElement: {
        prototype: HTMLViButtonElement;
        new (): HTMLViButtonElement;
    };
    interface HTMLViModalElement extends Components.ViModal, HTMLStencilElement {
    }
    var HTMLViModalElement: {
        prototype: HTMLViModalElement;
        new (): HTMLViModalElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "vi-button": HTMLViButtonElement;
        "vi-modal": HTMLViModalElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ViButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface ViModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isopen"?: boolean;
        "onAction"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "vi-button": ViButton;
        "vi-modal": ViModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "vi-button": LocalJSX.ViButton & JSXBase.HTMLAttributes<HTMLViButtonElement>;
            "vi-modal": LocalJSX.ViModal & JSXBase.HTMLAttributes<HTMLViModalElement>;
        }
    }
}
